blank_issues_enabled: false
contact_links:
   name: The Acronix98's Server
   url: https://discord.gg/Acronix98
   about: Please direct any questions, ideas etc. to the Discord Sever, if asked on GitHub it will go unanswered!
