blank_issues_enabled: false
contact_links:
   name: Support
   url: https://discord.gg/Acronix98
   about: Please direct any and all help requests to here. If a help request is on GitHub, it WILL go unanswered
